### ISSUE TITLE
acor module error

### ISSUE THREAD

**Issue by cmarsan** [dfm/acor#5]
Hi, I'm pretty new to python and am having an issue with acor that I thought I installed successfully (tried both pip install and git clone). I'm getting pretty similar errors as those listed in issue #4, and I need acor for a separate Python algorithm. I have Python 3.5.2  through Anaconda.

>>> import acor
>>> acor
<module 'acor' from '/localdir/anaconda3/lib/python3.5/site-packages/acor/__init__.py'>
>>> import numpy as np
>>> a= np.random.rand(500)
>>> acor(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable

Any tips?

**Comment by dfm** [comment]
Have you tried calling the `acor` _function_ instead of the module? The usage is given here: https://github.com/dfm/acor#usage

**Comment by dfm** [comment]
Also: I'd recommend checking out the `autocorr` module in emcee http://dan.iel.fm/emcee/current/api/#autocorrelation-analysis because it's a bit more reliable. `acor` will be marginally faster but it will probably only be worth it if you need to compute many autocorrelation times on datasets with billions of points.

**Comment by cmarsan** [comment]
If I call the acor function, I get:
AttributeError: module 'acor' has no attribute 'acor'

**Comment by dfm** [comment]
Sounds like it didn't get installed then. How did you install the package?

**Comment by cmarsan** [comment]
pip install acor

**Comment by dfm** [comment]
I dunno then. Try cloning from github and installing that way. No one has touched this project in 3 years so it's definitely use at your own risk! I'd still recommend the algorithm in emcee before this one.

**Comment by FrederikHeber** [comment]
This is the same issue as #4. My workaround (for python3.5 and newer) is to replace in *acor/acor.py*

    import _acor

by

    import acor._acor as _acor

Then the *acor* function can be used after importing as `import acor.acor as acor`.

Seems the pip package installed by

    pip3 install acor

(states to be acor-1.1.1) is out-dated, the Github code is more recent and fixes this?
